language: 
  - cpp
  - python

compiler: gcc

dist: xenial

before_install:
  - sudo add-apt-repository ppa:deadsnakes/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install python3.6 -y
  - sudo apt-get install python3.6-dev -y
  - sudo apt install libfreetype6-dev libxrandr-dev libudev-dev libogg-dev libflac-dev libvorbis-dev libopenal-dev
  - sudo apt install wget
  - wget https://www.sfml-dev.org/files/SFML-2.5.1-linux-gcc-64-bit.tar.gz
  - tar xvzf SFML-2.5.1-linux-gcc-64-bit.tar.gz
  - cd SFML-2.5.1 
  - sudo apt-get install cxxtest

script:
  - make
  - make test
  - ls src/*.h src/*.cpp | xargs clang-format -i && git diff --exit-code